# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: iKenWoo
email: ikenwoo@gmail.com
description: > 
  My two Canadian cents on programming, learning and all things awesome. 
  Please note that my pennies are now deprecated in my country.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ikenwoo.github.io" # the base hostname & protocol for your site
twitter_username: ikenwoo
github_username:  ikenwoo
timezone: America/Toronto

# Build settings
markdown: kramdown
