# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: iKenWoo
description: > 
  My two Canadian cents on programming, learning and all things awesome.
copyright: Ken Woo 2016
sass:
  sass_dir: assets/sass
url: "http://ikenwoo.github.io" # the base hostname & protocol for your site
google_analytics: UA-63017368-1
disqus_shortname: ikenwoo
twitter_username: ikenwoo
github_username:  ikenwoo
feed_icon: rss
email: ikenwoo@gmail.com
timezone: America/Toronto
gems: [jekyll-paginate, jemoji]
paginate_path: "/page/:num/"
paginate: 5

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      permalink: /:title